<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cssclass"
 *
 * Auto generated by Extension Builder 2014-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CSS Class',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Fehmi Raqipi',
	'author_email' => 'fehmi@raqipi.ch',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0.0-7.6.99',
			'fluid' => '6.0.0-7.6.99',
			'typo3' => '6.0.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
